name: CI/CD - Server

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

jobs:
  Client:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
      
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Heroku Deploy
    # You may pin to the exact commit or the version.
    # uses: CDNievas/heroku-action@c9cf9c85571e67583e44ec92c0d1113f66b0e838
      uses: CDNievas/heroku-action@v1.0
      with:
        # Used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${HEROKU_API_KEY}
        # Email from Heroku Account
        heroku_email: 'andigwandi@gmail.com'
        # The appname to use for deploying/updating
        heroku_app_name: 'inventoryapi'
        # The branch that you would like to deploy to Heroku
        branch: # optional, default is HEAD
        # Set this to true if want to use --force
        useforce: # optional
        # Set if your app is located in a subdirectory.
        appdir: './server'
        # Contents of the Procfile to save and deploy
        procfile: # optional, default is 
        # Set to true if you need upload files generated dynamically by the GitHub Action to Heroku
        dynamicFiles: # optional
        # Buildpacks to install on Heroku
        buildpacks: # optional, default is 
        # Path to an localized env file
        env_file: # optional, default is 